version: "3.1"
services:
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/code
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017